// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_de_Veiculos.Data;

#nullable disable

namespace Sistema_de_Veiculos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251111112410_CriarBanco")]
    partial class CriarBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_de_Veiculos.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AnoVeiculo")
                        .HasColumnType("float");

                    b.Property<string>("ModeloVeiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("TabelaVeiculos");

                    b.HasDiscriminator<string>("Tipo").HasValue("Veiculo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Sistema_de_Veiculos.Models.Carro", b =>
                {
                    b.HasBaseType("Sistema_de_Veiculos.Models.Veiculo");

                    b.HasDiscriminator().HasValue("Carro");
                });

            modelBuilder.Entity("Sistema_de_Veiculos.Models.Moto", b =>
                {
                    b.HasBaseType("Sistema_de_Veiculos.Models.Veiculo");

                    b.HasDiscriminator().HasValue("Moto");
                });
#pragma warning restore 612, 618
        }
    }
}
